### ISSUE TITLE
Canada.ca theme: Content page template Canada.ca Content and Information Architecture Specification

### ISSUE THREAD

**Issue by qanitah** [wet-boew/GCWeb#1065]
We are using Canada.ca theme Content page template for our web application. According to the Canada.ca Content and Information Architecture Specification, Generic destination pages template must have institutional byline component just right after the H1. We have following questions regarding the template.

1. Is the Generic destination page template referred in the Canada.ca specifications same as Canada.ca theme content page template(http://wet-boew.github.io/themes-dist/GCWeb/content-en.html)? 

2. If yes then do we need to apply the institutional byline as mentioned in the Canada.ca Content and Information Architecture Specification and do we need to apply that on every page of the application?

Thank you. 
![template](https://cloud.githubusercontent.com/assets/14280062/12985861/921b523a-d0c2-11e5-9026-b995cb12fabc.jpg)

**Comment by pcwsmith** [comment]
1. I think what you are seeing in the working examples isn't quite up to speed with the Spec. @shawnthompson is that right?
2. Intent for the byline element is to relate content pages on Canada.ca to the institution responsible for them. Would need to know more about your application to understand if including this would make sense in your case.

Thx

**Comment by qanitah** [comment]
Sorry for the delay.
Here is a URL which contains 3 similar applications. You can take a look at one of them and let us know your thoughts on whether the institution byline is required. 

http://healthycanadians.gc.ca/drugs-products-medicaments-produits/inspecting-monitoring-inspection-controle/inspections/index-eng.php

**Comment by DK-TBS** [comment]
Hi @qanitah!  Peter @pcwsmith and I just took a look at your applications, and we both agree that they would definitely benefit from having the institutional byline, as described in the spec.  That byline is intended to be present on all destination content pages, so users can always see which institution is responsible for the content.  

Also, just to confirm:  the [content page](http://wet-boew.github.io/themes-dist/GCWeb/content-en.html) that you referred to earlier is indeed the Generic Page Template, but as Peter mentioned, the one you see up there with the demo pages is out of date, and that's why it doesn't show the institutional byline there.  @shawnthompson and his team are working to bring those demo templates up to spec.

**Comment by qanitah** [comment]
Thank you for your help.
