### ISSUE TITLE
Mobile Search Results Squished by Long URL

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#1079]
Mobile usability participants struggled to use the search results yesterday, because the URL length of some of the URL's in the <span> is not wrapping properly, and instead is pushing the entire view into 'tiny mode'. This is not design-intent, it only happens for some search results that are incorrectly shortened. Shortening with the ellipse needs to happen at a shorter length. 

See image below - try it yourself by entering the search term 'employment'.  See screen shots below. 
- Also a warning to us all - didn't notice this until a participant tested it on their phone - in Developer View on Chrome it looked fine! 
  ![dev view combo](https://cloud.githubusercontent.com/assets/1855584/13464670/4074db88-e060-11e5-8bcb-d9693fd911bd.png)

**Comment by shawnthompson** [comment]
I found this:

[Handling Long Words and URLs (Forcing Breaks, Hyphenation, Ellipsis, etc)](https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/)

I recommend this:

``` css
.wb-wrp {
  overflow-wrap: break-word;
  word-wrap: break-word;
  word-break: break-word;
}
```

**Comment by shawnthompson** [comment]
Also Chrome wraps long URLs by default but Safari does not so that's why you didn't see the problem in your developer view in Chrome.

**Comment by neoinsight** [comment]
@shawnthompson @pcwsmith 
Dang, I get a 500 server error when I try to read that article. Will try again later. Two things: 
1. Does the css above wrap or break? because for search results, we don't want a wrap, we just want it to force the ellipse much sooner. That way they see the URL, but long urls don't wrap and disrupt the reading of the search results, make the page longer etc. There is a forced ellipse in place now, it's just not happening soon enough. 
2. Oddly, the Chrome developer view is not wrapping the long URL's by default, instead, they are simply being cut off - as below. That's why I thought there might be a new problem at the WET level, because I've watched people use search all year long, and never have seen this issue before. See image below - see the URL's getting cut off..
![image](https://cloud.githubusercontent.com/assets/1855584/13468824/9687c140-e072-11e5-91f6-f98e9c9a6b4f.png)

**Comment by shawnthompson** [comment]
This is what you get with the CSS rules above

![image](https://cloud.githubusercontent.com/assets/2575266/13469276/acbeef2c-e074-11e5-80cc-7a66a0a2f19b.png)

It will wrap and break the words at the end of the container.

**Comment by shawnthompson** [comment]
FYI
https://twitter.com/chriscoyier/status/705081222125457408

**Comment by shawnthompson** [comment]
@cfarquharson what are your thoughts on this? Adding a "wrap" class to the utitlity styles to force a wrapping of long text?

**Comment by neoinsight** [comment]
@shawnthompson - @pcwsmith and I spoke about this today. We prefer breaking the text and providing the ellipse, given that only the first part of the URL is needed. The Coyier article above suggests another advantage, which is that this 'text overflow' approach is universal, rather than browser specific.

**Comment by shawnthompson** [comment]
Would this be a good standard to have when putting a URL on as text on a page, would be to have it ellipse? I'm still very cautious about putting URLs on webpages due to accessibility concerns. They are never to be used as link text. Personally I'd like to see it only put the domain instead of the full link if you say people only look to validate it's actually coming from a gc.ca site.

**Comment by pcwsmith** [comment]
Agree that as a general rule we don't want to show URLs on our pages. But the Canada.ca SERP UI is a special case, in that we want it to conform as much as possible to established conventions for web search.

As for the domain - I think we need to stick with presenting URLs, otherwise far too many search results will basically only show the exact same thing, ie www.canada.ca. (thinking post onboarding here)

In terms of number of lines on the screen that the URL takes up in each search result, right now the spec sez that URLs in search results should be no longer than 95 characters including the elipsis.... this is based on a large screen display. 

Thinking we should actually amend the spec requirement to say that no matter the screen size, the URL portion of the search result should only take up one line, including the ellipsis...thoughts?

**Comment by neoinsight** [comment]
Closing - issue was moved to GCWeb-search repository. See above

**Comment by neoinsight** [comment]
Unclosing  - other repository is temporary.

**Comment by hsrudnicki** [comment]
Does this remain still an issue or otherwise?  Please update the status/milestone of this again, thx

**Comment by pcwsmith** [comment]
we've got this on our to-do list for the SERP UI in the Spec:

> amend the spec requirement to say that no matter the screen size, the URL portion of the search result should only take up one line, including the ellipsis

**Comment by neoinsight** [comment]
Closing this issue - it appears the search results table has been made wider, so can just scroll over to the right to see entire url, not squishing results anymore.
