### ISSUE TITLE
Basic HTML version - Carousel Items

### ISSUE THREAD

**Issue by Robineast** [wet-boew/GCWeb#1081]
@wet-boew/access-working-group 
The Basic HTML Version does not offer the same information as the standard version. Under Promotion in the carousel displays only the one tab in the Basic HTML Version and not all of the tabs. It is always the first tab regardless whether or not the carousel is paused or in play. 

A number of the graphics has the alt text set as: alt="null" Maybe these should be empty or have proper alttext

**Comment by hsrudnicki** [comment]
Is this still an issue? Please update the status of this, whether this can be closed or otherwise, thank you

**Comment by EricDunsworth** [comment]
wet-boew/wet-boew#7815 should fix what's left of this issue, since it restores all hidden carousel panels in noscript and wbdisable (basic HTML) scenarios.

As for ``alt="null"``... I can't currently find any sign of it in wet-boew, GCWeb, nor Canada.ca's real home page. So I presume that's no longer an issue.
