### ISSUE TITLE
Canada.ca theme: Section menu examples template

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/GCWeb#1144]
Hi,
The section menu example template (http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html) has header as a hyper link where as the Canada.ca Content and
Information Architecture Specification (v1.3.1) indicates it should be "A non-clickable header, identifying the immediate parent of the current page".

Please confirm  whether it should be a hyperlink or not.

Thanks

**Comment by DK-TBS** [comment]
Hi Sarasuri!  Thanks for catching that.  When those menus were first conceived, that header item was supposed to be non-clickable - but after feedback from the community, we changed that to make the first item into a link, as you see in the example template you mentioned.

The example template is doing it right.  The first item should be a link.  The spec is wrong, the way it describes that element.  We'll correct this in the next version of the spec document.  

Appreciate you pointing it out, we might never have noticed the error otherwise  :)
