### ISSUE TITLE
Section Menu missing in GCWEB theme since v4.0.21

### ISSUE THREAD

**Issue by sylus** [wet-boew/GCWeb#1148]
If you go to:

http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html

and change to mobile view you won't see the section menu appear. However if you go to any of other themes the menu will appear. I have traced it to this line:

https://github.com/wet-boew/GCWeb/compare/v4.0.20...v4.0.21#diff-73087d4be190b9d2b15b56f9a2b8229dR251

https://github.com/wet-boew/GCWeb/blob/master/src/menu/_base.scss#L251

Why was display: none added to this?

**Comment by DK-TBS** [comment]
I wasn't involved in the coding of the thing, but - if you narrow your browser window, you should see the menu move down just below the main page content.  

The decision was made to move the local nav menu out of the mobile menu to the bottom of the page, because testing revealed that people have an easier time finding it there.

**Comment by sylus** [comment]
I am talking about the mobile flyout under mb-pnl it doesn't show when you toggle the hamburger icon.

**Comment by DK-TBS** [comment]
It does seem to work a lot better for visitors this way.  Not sure about whether it was mentioned in the release notes though, I haven't actually been involved in that side of things...

**Comment by shawnthompson** [comment]
I don't think we mentioned it in the release notes but I'm sure it's mentioned in the IA Specs that @DK-TBS works on...

**Comment by sylus** [comment]
Thanks a bunch! Nothing to action here then ^_^

Closing issue!
