### ISSUE TITLE
Secondary navigation in print

### ISSUE THREAD

**Issue by rlambert27** [wet-boew/GCWeb#1204]
Our development team noticed a bug in WET since v4.0.22 where the secondary navigation is being displayed when doing a print.

Example in v4.0.21 : http://www.cic.gc.ca/english/citizenship/become-eligibility.asp (not showing up)
Example in v4.0.22 : http://srv130.services.gc.ca/index/eng/about.aspx
Example in v4.0.24 : http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html

I don't believe this was intentional but probably a bug that was introduced when the secondary navigation was moved out of the hamburger menu to the bottom of the page.

Thanks!

/cc @karinne

**Comment by EricDunsworth** [comment]
I have a downloaded production package of GCWeb v4.0.21 kicking around somewhere. In its version of http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html, the secondary navigation menu appears when printing.

The reason the secondary navigation menu appears when printing pages on CIC's site is because it's using a custom CSS file (http://www.cic.gc.ca/css/bootstrap-equivalence.css). A nearby comment indicates it's meant to fix an "IE PRINTING FORMAT ISSUE".

In any case, I'll send over a PR to hide it in GCWeb since it doesn't make sense to show it. It's not part of the main content area and WET/GCWeb's pre-existing CSS already hides just about everything else that isn't main content. The [secondary menu is already hidden in the WET theme's print CSS](http://wet-boew.github.io/v4.0-ci/theme/content-secmenu-en.html), too.

**Comment by EricDunsworth** [comment]
#1207 fixes this.
