### ISSUE TITLE
Odd left/right arrow key behavior in menubar

### ISSUE THREAD

**Issue by carmacleod** [wet-boew/GCWeb#1335]
Reposted from https://github.com/canada-ca/canada-ca.github.io/issues/34

Issue part 1:

1. Go to https://www.canada.ca/en.html
2. Using only the keyboard, navigate to the menubar; the Jobs menu opens
3. Type right arrow; the Immigration menu opens
4. Type down arrow a couple of times; you are on the Visit menuitem
5. Now type right arrow

The expected behavior is that the menu to the right (the Travel menu) would open.
Instead, surprisingly, the Jobs menu (the one on the left) opens.

Issue part 2:

1. Repeat steps 1 - 4, above
2. Now type left arrow

The expected behavior is that the menu to the left (the Jobs menu) would open.
Instead, quite surprisingly, the Taxes menu (way over on the right) opens.

**Comment by shawnthompson** [comment]
@carmacleod This seems to be a problem with the Canada.ca implementation of the WET menu. It seems to work as expected on the [GCWeb examples](http://wet-boew.github.io/themes-dist/GCWeb/index-en.html).

@duboisp Can you advise the Canada.ca team of the problem?

**Comment by duboisp** [comment]
@carmacleod Thank for clear description. The step by step was very helpful.

I though that updating the WET / GCWeb version to the latest on Canada.ca would solve this issue, but after testing it won't.

So, I tracked the bug until I reach this line
https://github.com/wet-boew/wet-boew/blob/master/src/plugins/menu/menu.js#L750

During the execution of your scenario I found that jQuery selector are returning no element. So when the function "MenuIncrement" is called, there is no reference passed about what current menu is selected. So when it does some Math operation to know which menu is next, it either go on the first item (when using the left arrow) or go on the menu before the last item (when using the right arrow)

The menu implementation are not the same on GCWeb vs Canada.ca. On Canada.ca the top level menu item are set to real link instead of anchor. They are set to real link in order to get the menu working in the Basic HTML Mode.

**Comment by carmacleod** [comment]
Interesting! So what would the fix be? I guess you can't change Canada.ca to use anchor?
Can you change the code to work with either anchor or link?
i.e. maybe if there's no reference for current menu for anchor, try looking for link reference?

(I'm just guessing, based on your explanation. ;)

**Comment by duboisp** [comment]
I am looking at various option.

But I will most likely send a PR in WET that would change the code to work with either anchor or link.

**Comment by carmacleod** [comment]
You just never know how users will use your stuff!  :)

**Comment by duboisp** [comment]
> Interesting... I still blame Canada.ca!

The real issue is the enhanced template for the mega menu plugin are not very well documented. In fact, you need to reverse engineering the javascript code combined with the live DOM to know what it is about.

For WET 5, I am looking for a stronger documentation of any template use by plugins.

**Comment by zzucco** [comment]
I've made a fix and put in a pull request in WET. (#8395)
The fix changes [line 750](https://github.com/wet-boew/wet-boew/blob/master/src/plugins/menu/menu.js#L750) to look for a link in the menu's siblings instead of looking for a something with a specific ID.

Once the PR is accepted, I believe we can close this issue.

**Comment by duboisp** [comment]
reference: https://github.com/wet-boew/wet-boew/pull/8395
