### ISSUE TITLE
Bug - Breadcrumbs syntax aren't working

### ISSUE THREAD

**Issue by rgalipeau** [wet-boew/GCWeb#1943]
## Describe the bug

Adding breadcrumbs isn't working, even pages in these templates with existing multiple levels are not loading corrently: 
See on 'https://github.com/wet-boew/GCWeb/blob/master/templates/topic/topic-testcase-1-en.html'

## To Reproduce

Steps to reproduce the behaviour:
1. Go to 'https://wet-boew.github.io/GCWeb/templates/topic/topic-testcase-1-en.html'
2. See error "}" rendering, and no 2nd level breadcrumbs are loading.

## Example

The code is there, and looks ok, but does not generate multiple breadcrumbs:
```
	"breadcrumb": [
		{ "title": "Canada.ca", "link": "https://www.canada.ca/en.html" },
		{ "title": "[Theme Name]", "link": "theme-testcase-1-en.html" }
	],
```
Same scenario for https://wet-boew.github.io/GCWeb/templates/service-en.html

**Comment by rgalipeau** [comment]
Thanks @EricDunsworth 
This worked!

**Comment by EricDunsworth** [comment]
@rgalipeau You're welcome :)!

Btw #1945 only fixes breadcrumb and language toggle linking issues. That's why I wrote its commit in a manner that only referenced this issue (wouldn't of closed it upon getting merged).

Unfortunately, #1945 won't fix the the second ``}`` H1 in the [topic test case 1 page](https://wet-boew.github.io/GCWeb/templates/topic/topic-testcase-1-en.html) nor the numerous other issues that exist throughout GCWeb's older pages.

The GCWeb repo used to be setup very similarly to the WET repo. WET uses handlebars and grunt to generate its pages. GCWeb used to be the same deal, but in recent times was restructured to use Jekyll going forward. But it looks like a lot of handlebars-era stuff hasn't been adapted to Jekyll as of yet. So a lot of older page templates/etc are kind of broken atm.
