### ISSUE TITLE
Left navigation: Round 2

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/GCWeb#776]
This is a continuation from https://github.com/wet-boew/wet-boew-styleguide/issues/71.

We need to discuss the need / use of a left menu on Canada.ca.

I've always been told that there was no need or want for a left menu on Canada.ca but from what I can see many sites that are still using a left navigation. [cic.gc.ca](http://www.cic.gc.ca/english/immigrate/apply.asp), [healthycanadians.gc.ca](http://healthycanadians.gc.ca/eating-nutrition/food-guide-aliment/index-eng.php) and [travel.gc.ca](http://travel.gc.ca/returning?_ga=1.240887946.804993619.1410354722), although Travel will be removing theirs with the new update.

The sites that are still using the left menu are not using them as per what was suggested by the [previous closed issue](https://github.com/wet-boew/wet-boew-styleguide/issues/71).

We are still maintaining [sample pages](http://wet-boew.github.io/themes-dist/GCWeb/partners/index-en.html) for those site that use left navigation and due to the latest changes you can see that the **Government of Canada activities and initiatives** sections are pushed to the right and in the content area of these pages now.

I would like to have something written down to help any adopters of this GCWeb theme with the decision of what to do with their left navigation.

**Name dropping time**

@pjackson28, @masterbee, @cfarquharson, @rubinahaddad, @thomasgohard, @nrustand92, @patlaj, @pcwsmith, @MRicher

**Comment by hsrudnicki** [comment]
@shawnthompson @thomasgohard @pcwsmith @masterbee  @rubinahaddad: can we finalize/tackle the issue discussion to close it?
Based on your above discussion:
- This issue #776 is about "the need / use of a left menu on Canada.ca" that results in offering at least two possibilities: using a left navigation or/and not using a left navigation, it's mostly depends on the designed structure and content of web site page(s), and as well what either we developers, and client as well as recipient/public want
-The issue #6502 is about coding details "on how to implement the secondary menu", if we decide/implement the left menu

**Comment by hsrudnicki** [comment]
@shawnthompson @thomasgohard @pcwsmith @masterbee @rubinahaddad @SLaverty:
Here is the third issue #976, just raised recently, and referencing to this issue with a strong argument of not using the left navigation menu due to Mobile structure constraints, additionally to this, see Google material design: http://www.google.com/design/spec/layout/structure.html#structure-ui-regions that may help you in making your decision and closing the issue(s)

**Comment by hsrudnicki** [comment]
@shawnthompson and others: Just by occasion as this issue is dependable on others, are you ready to close this issue?

**Comment by hsrudnicki** [comment]
Based on the last comment from @shawnthompson : Is this still an issue? Please update this issue's status, whether this issue can be closed as resolved/fixed or otherwise? If otherwise, label this issue as "Going Stale", and what status update in case of the referenced opened issue?
Thank you in advance for your update(s)

**Comment by shawnthompson** [comment]
I guess we can close this issue too. 

[Local navigation](http://wet-boew.github.io/themes-dist/GCWeb/localnav/task1/index-en.html)
