### ISSUE TITLE
Government of Canada activities and initiatives (former Features): images not top aligned

### ISSUE THREAD

**Issue by biljanap** [wet-boew/GCWeb#787]
If h3 text for all 3 images does not contain the same number of lines, images are not top aligned.

![features](https://cloud.githubusercontent.com/assets/2146304/4342048/113c458e-4040-11e4-86fd-3e811ad31395.jpg)

**Comment by LaurentGoderre** [comment]
Twitter character limit is not based on visual constraint bit rather from the technical constraint of SMS. In this case the limit is printed character, not underlying bits.

**Comment by masterbee** [comment]
@hsrudnicki  - agreed with @LaurentGoderre that character counting in Twitter is a bit off the mark on this thread. We are simply trying to set a visual character limit for the design. We will wait back from ok from @pcwsmith so we can close this issue up with a resolution.

**Comment by pcwsmith** [comment]
all good, thanks everyone!

**Comment by hsrudnicki** [comment]
@pcwsmith, if all good and explained, can this issue be closed or otherwise?
[Note: Just by occasion for setting the visual character limit, based on http://english.stackexchange.com/questions/2998/do-most-languages-need-more-space-than-english, French texts are longer than their English counterparts by about 1/5 to 1/4, but anyway you will decide about the estimate number(s).]

**Comment by hsrudnicki** [comment]
@biljanap @LaurentGoderre @masterbee - Can be the issue closed?
Up to now, the following had been fulfilled:
- @pcwsmith expressed his OK for the resolution of putting character limit(s) for the design
