### ISSUE TITLE
Canada.ca includes Google Tag Manager twice

### ISSUE THREAD

**Issue by LaurentGoderre** [wet-boew/GCWeb#802]
In the theme code, all is well but in Canada.ca Google Tag Manager is called twice with different ID

``` html
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-MG4LMJ" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-MG4LMJ');</script>
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-TLGQ9K" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer1'?'&l='+l:'';j.async=true;j.src='//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer1','GTM-TLGQ9K');</script>
```

**Comment by hsrudnicki** [comment]
@lucas-hay @LaurentGoderre @shawnthompson : can we this issue finilize/tackle in order to close it?
Based on your discussion:
-  each id has to be unique
-  rename the dataLayer for one of the containers (developers.google.com/tag-manager/devguide#renaming) least the two datalayers interfere with each other (see for example here: stackoverflow.com/questions/17718483/…)
- also Google does not recommend multi - Google Tag Managers on a web page, see https://support.google.com/tagassistant/answer/3207128?hl=en#multiple_tags, due that "Multiple GTM snippets do not work well with each other because of which the tag added via GTM may not always fire correctly."
- for example, based on https://developers.google.com/tag-manager/devguide#multidomain, "it's recommended that each separate web property that you manage be deployed with its own container,  however, when multiple Top Level Domains or subdomains are considered to be members of the same website, it may be beneficial to manage their tags through the same Google Tag Manager container."

**Comment by LaurentGoderre** [comment]
We should leave this open until we find a better solution because this still is an issue

**Comment by hsrudnicki** [comment]
Please update again this issue's status, whether this issue's status does remain as open(ed) or if otherwise?  In addition, label this issue as "Going Stale"?  Thank you for your update(s)

**Comment by hsrudnicki** [comment]
Please update this issue's status for the current year, thank you

**Comment by lucas-hay** [comment]
Closing this issue as we have removed one of the GTM containers.
