### ISSUE TITLE
Widget page:  H3 headings

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#921]
http://wet-boew.github.io/themes-dist/GCWeb/widgets-en.html

http://wet-boew.github.io/themes-dist/GCWeb/widgets-fr.html

Third column, at far right: the H3 headings are rendering larger than the H2 headings… they probably don’t need to be quite so large. (Or maybe it’s just a rendering bug in IE9)

**Comment by shawnthompson** [comment]
I'm on it!

**Comment by hsrudnicki** [comment]
@DK-TBS @shawnthompson :  Has been the issue in regards to heading content in an element of sectioning content solved and it's ready to be closed?
Based a very similar problem on http://stackoverflow.com/questions/6851833/h1-is-smaller-than-h2-in-firefox-and-chrome, see at http://www.whatwg.org/specs/web-apps/current-work/multipage/sections.html#headings-and-sections and the style rules at http://www.whatwg.org/specs/web-apps/current-work/multipage/rendering.html#sections-and-headings

**Comment by hsrudnicki** [comment]
Into your consideration to check/make sure if this issue is not affecting the following:
https://github.com/wet-boew/wet-boew/issues/6809 - Changes to WET Core and Themes to simplify implementation by variants
https://github.com/wet-boew/wet-boew/issues/5182 - Demo files for each language in each theme
https://github.com/wet-boew/wet-boew/issues/5945 - Heuristic Evaluation - Canada.ca's Gallery Layouts

**Comment by hsrudnicki** [comment]
also related to https://github.com/wet-boew/wet-boew/issues/4965

**Comment by shawnthompson** [comment]
Maybe I'll do this finally, sorry it fell in the cracks.

**Comment by hsrudnicki** [comment]
@shawnthompson : Based on the above, is this still an issue?  Either way, please update this issue's status whether this can be closed as fixed or if otherwise? Thank you
