### ISSUE TITLE
Feedback form page:  little tweaks

### ISSUE THREAD

**Issue by DK-TBS** [wet-boew/GCWeb#922]
- Can we just add a little bit of breathing room between the intro paragraph and the form? Maybe a little margin-top
- Let’s remove that reset button. People aren’t likely to need it, but they are likely to push it accidentally.

**Comment by shawnthompson** [comment]
This form is exactly the same as the [WET validation form](http://wet-boew.github.io/v4.0-ci/unmin/demos/feedback/feedback-en.html) and I think it should be removed.

Maybe we can link to the compiled demo pagess with the GCWeb theme applied that's included in the build.

http://wet-boew.github.io/themes-dist/GCWeb/demos/index-en.html
http://wet-boew.github.io/themes-dist/GCWeb/demos/index-fr.html

This would mean we can get rid of the video page also.

Thoughts?

**Comment by DK-TBS** [comment]
That makes sense to me.  Would it be much work to bring it back, in case someone complains about the fact that we removed it?

**Comment by shawnthompson** [comment]
It's just a straight copy and paste from WET but even that we can always roll back with git.

**Comment by pjackson28** [comment]
Note that there is a difference between the GCWeb and the WET core versions. The GCWeb version has the GC-specific notices that are required by the Standard on Web Usability (privacy, etc) while the WET core version does not (since they don't make sense for non-GC sites).

**Comment by DK-TBS** [comment]
Ah, okay better leave it in place then.  Thanks Paul!

**Comment by shawnthompson** [comment]
So I should put it back...

This form is not the same as the form on the actual Canada.ca site

http://www.canada.ca/en/contact/feedback.html

Does that matter?

**Comment by DK-TBS** [comment]
Whoa, those are totally different.  Looks like someone put extra thought into the one that's on canada.ca... surely it's not supposed to be replaced with this little generic one here.  

Maybe this one is intended for other parts of the site, maybe feedback forms specific to certain services/programs/departments?  I don't actually know where it came from, or what it's for...

**Comment by shawnthompson** [comment]
Something @masterbee put on a while back

**Comment by pjackson28** [comment]
The one in WET is actually not that generic when you try to report a problem (see http://wet-boew.github.io/v4.0-ci/demos/feedback/feedback-en.html#web which auto-selects the "Critical problem with the website"). That was the main focus of the one in WET. The one on Canada.ca is very weak on the problem reporting (just a generic free form field) and is also missing anything to do with following up on any comments (since there is no possibility of providing contact information so no possibility of getting more details). Also there seem to be no notices either (possibly because of the lack of opportunity of providing contact information).

So if you want to get any useful information to resolve problem reports with the website, I suggest you incorporate that portion of the WET feedback form.

**Comment by pjackson28** [comment]
Sorry, got the hash wrong. Just select "Critical problem with the website" to see what I mean. That was built by the community to deal with the huge headaches of having inadequate information to resolve problems reported through feedback forms.

**Comment by shawnthompson** [comment]
I will pass the word on, kind sir.

Or maybe @nrustand92 can?

**Comment by DK-TBS** [comment]
Hey, that *is* pretty great... lots more detail in there.  Good stuff!

**Comment by nrustand92** [comment]
@shawnthompson Thanks for including me in the conversation

@pjackson28 @DK-TBS We're taking an iterative approach to continuously improve the site.  Just so you know @pjackson28 the report a problem/suggest an improvement section is modeled after Gov.uk https://www.gov.uk/contact/govuk  and while I don't want to point my finger at anyone or name anyone, let's just say that was not my decision to have it looking like that. FYI, New Zealand government is taking a similar approach too, but they have the radio buttons at the top: 
govt.nz/about/feedback/

My boss and I are working on the next stage of improvement and I've used some ideas from the GCWeb Feedback Form mechanism. I especially like the dropdown at the top.

**Comment by nrustand92** [comment]
Also, @pjackson28 due to privacy issues we're not giving an option to reply, but that's an option we want to have in the future.

**Comment by pjackson28** [comment]
That's odd that the option to reply was left off due to privacy issues since that can be addressed through the Personal Information Collection Statement and privacy notice included in the GCWeb example (which are required by the Standard on Web Usability).

Looking at the UK model, I see that it includes:
* Opportunity to request a reply (by providing the name and email address)
* Opportunity to provide more detailed information if something went wrong ("What you were doing", "What went wrong") - Although those fields are very easy to miss since they are collapsed by default and only available through an easily missed link at the bottom of the form.

I understand the need to keep forms simple, but there needs to be a balance as there is nothing more frustrating than a lot of back and forth to try to figure out what is actually wrong. It is good to provide the user the option to provide more information if they can (to save a couple of back and forths or to make it easier to make a quick diagnosis). Not a big deal when it is non-technical issues (unclear content) but can really cut down the back and forths for more technical issues (e.g., page did not display properly, browser crashed, too hard to read certain content, etc).

**Comment by nrustand92** [comment]
@pjackson28 thanks for the feedback, I'll definitely take that into account for the next round of improvement. There is a plan that we may have different feedback categories. And correction for the reply thing, I've always assumed it's a privacy problem, but I checked again turns out it's an HR problem...we're not fully staffed for that, but it's a good idea to be able to reply to users.  I'm aware that many other gov website have that option.

**Comment by pcwsmith** [comment]
just circling back to the reset button: spec sez that you should avoid secondary actions whenever possible - pretty much for the reason that @DK-TBS described at the top of this thread. So regardless which form, "reset" buttons should disappear!

**Comment by pjackson28** [comment]
@thomasgohard Any comments on the request to remove the reset button?

**Comment by nrustand92** [comment]
Just an article on why Reset button should be avoided:
http://bfma.typepad.com/blog/2010/04/avoid-reset-buttons-on-forms.html

**Comment by DK-TBS** [comment]
I agree with the author, obviously.  Though her reasoning seems sound, she doesn't present any evidence, but... neither do I.

I'm not sure we need any.  Instead, perhaps this question can be answered like this:  can any of us dream up any cases in which a user might actually want a reset button, or benefit from having one?

I sure can't.  I mean, it has its proper place in situations where the form is being used to alter/edit an existing data record... user makes a few changes, then has regrets, and wants to revert the data to the way it was before they started messing with it.  Clear need for a reset mechanism there, makes sense.

But in this case, I can't think of any use for it.  Perhaps my imagination is just failing me here, but I doubt it   :)

**Comment by thomasgohard** [comment]
There are problems with all the forms. I'll post a summary of the problems in the next couple of days. We can then look at how we want to address them.

**Comment by thomasgohard** [comment]
I've reviewed the WET feedback form and posted my recommendations (https://github.com/wet-boew/wet-boew/issues/6626). These also apply to the GCWeb feedback form. Except for the parts that have been removed, obviously.

I'll post my review of the Canada.ca feedback form shortly.

**Comment by thomasgohard** [comment]
The Canada.ca feedback form mixes two separate tasks: Rating the Web site and reporting a problem with the Web site. These two tasks should be separated into two separate forms, with appropriately descriptive titles and submit buttons.

For the rating task, use radio buttons instead of select elements and group the questions into related groupings (e.g., IA, content quality, etc.).

For the report a problem task, why limit the details to 250 characters?

**Comment by shawnthompson** [comment]
@thomasgohard I would like to test the likert scale (rating) for accessibility. I searched online on the best way to do one of these scales for accessibility and what I found was that select elements were better for screen readers.

[an old thread (2007)](https://www.mail-archive.com/wsg@webstandardsgroup.org/msg32119.html)

I also wonder what a scale like this look like in mobile?

**Comment by thomasgohard** [comment]
That thread doesn't quite say that select elements are better than radio buttons; it's just offered as an alternative. And there's no data to back it up as a better option. Considering select elements have know usability and accessibility problems, I'm not sure how they would be a better option.

And, while the technology wasn't quite what it is today back in 2007, I don't see why we can't make an accessible likert scale today using a combination of HTML and ARIA.

**Comment by LaurentGoderre** [comment]
What are the known accessibility issues with select fields?

**Comment by thomasgohard** [comment]
People lacking fine motor control have issues using them.

**Comment by LaurentGoderre** [comment]
in selecting the options you mean? Otherwise it's just the same as a text field to select, and the arrows makes them very easy to use.

**Comment by thomasgohard** [comment]
Yes, for selecting the options. Using a pointing device (e.g., mouse).

There's also usability issues because the process of making a selection using a select element is more complex than with a radio button (or checkbox for multiple options). Select elements are a compromise when screen real estate is an issue: They can fit more options is less space, at a cost to usability and accessibility for certain audiences.

**Comment by LaurentGoderre** [comment]
There's got to be a point where to many radio buttons becomes worse than a select element though In would assume.

**Comment by pjackson28** [comment]
@thomasgohard The biggest issue with radio buttons is when you apply a global label using fieldset/legend. With radio buttons you hear the legend text repeated for every radio button (very verbose). You can assign it to just the first radio button to reduce the verbosity but that is not helpful when the user navigates back up to the radio buttons. As for select, it is naturally less verbose (only announces the label once for the select element and not for each option) and is not vulnerable to the direction the user reads the options.

So pretty much you are introducing potential accessibility and usability issues with either approach (neither is a clear winner) so it is just a matter of which user group benefits the most/least (e.g., visual versus non-visual).

**Comment by thomasgohard** [comment]
Yes and no. Even a select element will be unusable when there are too many options. The problem is having too many options.

That being said a large group of radio buttons that's poorly laid out can be worse than a select element.

**Comment by thomasgohard** [comment]
@pjackson28 I agree. There are drawbacks to the fieldset/legend pattern for screen reader users (especially with Voice Over, as I'm discovering right now, which speaks the legend twice after each radio button).

I'm currently testing some patterns to try to mitigate that.

**Comment by nrustand92** [comment]
@thomasgohard @pjackson28 @LaurentGoderre @shawnthompson thanks for all your input.  @thomasgohard would you be able to share anything from testing the patterns?  Also thanks for the suggestion to separate the rating from the reporting.  Nick and I will consider/test the idea.

**Comment by thomasgohard** [comment]
@nrustand92 I'm building the patterns in https://github.com/thomasgohard/accessible-likert-scale. I'll add my notes in that repo as well as I test things with various screenreaders.

**Comment by nrustand92** [comment]
@npjontek please chime in as I'd love to hear your thoughts on this feedback form issue

**Comment by thomasgohard** [comment]
@nrustand92 I published my notes from my first round of testing: http://thomasgohard.github.io/accessible-likert-scale/. I'll keep updating the repo as I continue testing.

**Comment by nrustand92** [comment]
@thomasgohard thanks for sharing!

**Comment by hsrudnicki** [comment]
@DK-TBS @nrustand92 @shawnthompson @LaurentGoderre: Can we close the issue?

**Comment by nrustand92** [comment]
@ThomasGohard any updates?

**Comment by thomasgohard** [comment]
I've had to put this on hold for now due to other priorities. In the meantime, lets leave this open.

**Comment by nrustand92** [comment]
Ok

**Comment by patlaj** [comment]
Hi - I guess I'm bumping this because I'm hoping to get rid of the reset button too. I was going to create a separate issue about it but found my way here instead. 

The problem is that people look to the examples as how they should do things. We seem to have pretty universal agreement that reset buttons are more likely to hurt than to help. If they stay on the example forms, people will think they should include them on their forms too. 

Is it possible to make that change without involving any of the other issues that may take longer to decide on?

**Comment by hsrudnicki** [comment]
Due to no further discussion, is this still an issue, and additionally label this as "Going Stale"? Please update this issue's status with the referenced issue 6626, whether the issue(s) can be closed or otherwise? Thank you

**Comment by hsrudnicki** [comment]
Can be this issue closed or otherwise? If otherwise, please update this issue's status for this year, thank you

**Comment by DK-TBS** [comment]
Nudge, nudge.  If [this demo page](http://wet-boew.github.io/themes-dist/GCWeb/demos/feedback/feedback-en.html) is going to stay up for all to see, can we remove that "reset" button?  I still see these things all over the place, and I'm not sure why.  Let's do what we can to discourage them.

**Comment by MaximMartel** [comment]
removed the reset on the demo page that you mentionned @DK-TBS
