### ISSUE TITLE
GC Web Form Validation Demo Needed

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#958]
@thomasgohard In recent usability tests, the Next and Previous buttons worked well. Following the Primary/Secondary button design pattern, and the order suggested in previous research,  Next was on the right as the primary button, and Previous on the left as the secondary button. There were no errors and people used these buttons quickly and easily. They looked like this: 
![previous next buttons](https://cloud.githubusercontent.com/assets/1855584/6753777/e9392cbc-ceee-11e4-878b-3a30ee13a465.png)

But on the final page of the form, the primary Submit button was presented on the left, with the Previous button on the right as secondary. This caused some people to accidentally click Previous instead of Submit - they lost their work on that page, and had to re-enter it and then click Submit. The people who made the mistakes mentioned they were used to clicking on the right-most button, and that the "Previous button had moved".  It looked like this (I've exed it out so no one glances and thinks this is the correct order!).
![submit previous incorrect order](https://cloud.githubusercontent.com/assets/1855584/6753873/91ce13f6-ceef-11e4-93fe-e4e97ef92c63.png)

I'd like to recommend that the Form Validation Examples on WET demos have three pages so that everyone can see the recommended order for the buttons, and to prevent mistakes like the one I made!  Or make a separate one that captures the recommendations for Date of Birth etc. that is purely for Government of Canada. Perhaps we could just change the form we already made. 

@dknight, @pcwsmith - pulling you in to think about this idea of turning the form used for testing into a GC interactive form demo. 

The recommended order would be:
Page 1: Next (no Reset button unless it's a form that is a single page to use and re-use)
Page 2: Previous (secondary), Next (Primary)
Page 3: Previous (secondary), Submit (Primary)

**Comment by thomasgohard** [comment]
I agree, the primary and secondary actions should always be in the same order across forms and pages of a form.

Would we have an opportunity to test with the order reversed (primary action on the left and secondary action on the right)? I'm curious to see whether people are as successful with that ordering.

The reason I'm asking is because putting the primary action on the right makes it the second item in the tabbing/reading order. Ideally you'd want the primary action first. We can use CSS to change the order and have the tabbing/reading order with the primary action first, but then it may confuse keyboard users when the tabbing goes in the opposite direction just for the buttons.

**Comment by neoinsight** [comment]
Hmm, I see your point for tabbing. But other research (see http://www.slideshare.net/cjforms/buttons-on-forms-and-surveys-a-look-at-some-research-2012?related=1 for a summary) tested the primary on the left (which is the NEXT button on most pages). The study showed problems with that because people associate next with forward (to the right) and previous with Back (to the left - since it does much the same thing as the Browser Back button and those show a left arrow). 

Based on that, and the power of directional models, breaking that convention of Previous on left/Next on right is not a good idea at all.

**Comment by LaurentGoderre** [comment]
@thomasgohard why can't they visually be the way @neoinsight suggests but have the order in the DOM reversed and use CSS to position them? It's not guaranteed it would work but it would be worth testing.

**Comment by neoinsight** [comment]
@LaurentGoderre Good idea! There are plans to do more testing with screen-reader users in the next contract (with who-ever!). Testing the form elements and process, once the improvements have been made to all of them, including the datepicker, should be part of that, but it will be up to @pcwsmith.

**Comment by LaurentGoderre** [comment]
We are experiencing some serious delays to the datepicker progress unfortunately. This week has been a very bad one for this.

**Comment by neoinsight** [comment]
@LaurentGoderre No problem! Next testing won't be until well into April - new contract etc.

**Comment by dknight** [comment]
I guess i am involved in this topic by mistake?

**Comment by thomasgohard** [comment]
@LaurentGoderre that's what I suggested (last sentence).

@dknight yes. That should have been @DK-TBS getting tagged.

**Comment by thomasgohard** [comment]
@neoinsight most of the studies linked to from that presentation, including the presentation itself, conclude that the primary action should be on the left. It's only the two Census studies that mention anything about have "previous" on the right and "next" on the left, and that's because of users stating the alternative felt wrong, not because they couldn't complete the task.

I think that part of the reason for the difference is due to labelling and the expectations of directionality that comes with the "previous" and "next" labels. I think that if we used different labels, that break the expectations of directionality, we may have different results. For example, with the labels "continue" and "edit previous answers" would probably break the expectations of directionality. I'd love to run a study to see.

That being said, all studies found that either order worked. What really matters is that both actions are to the left and that the primary action is more visually salient than the secondary action.

Still, some study into the effect of expectations created by the wording of the labels could be useful to create additional guidance regarding the choice of labels for different scenarios.

**Comment by neoinsight** [comment]
@thomasgohard Agree that actions should be on the left and primary action more visually salient. Actions on left is also better for visually impaired people - they tend to scan down the left of the page.

You say "either order worked" but I don't think the data in the study related to Next & Previous did work. The big Couper study recommended Previous on the left.  The Romano next/previous study cited only had 8 participants.   We just ran 24, and 2 clicked Previous accidentally when it was on the right, missing the primary Submit button on the left.

That 'dissatisfaction' they felt was from having to think about something contrary to convention - and that thinking time is clearly evident in the Couper study.  When you have enough participants and you force them to think and be dissatisfied,  you see the failures start to happen. 

I see your point about directionality and the labels. But 'continue' implies directionality too - it's the Browser Back button that is creating the directionality expectation. It's very tough to break that kind of implicit expectation - they're surprisingly persistent. 

You're right, some study could be useful. In the meantime, sticking to conventions is best.

**Comment by hsrudnicki** [comment]
@neoinsight @thomasgohard @LaurentGoderre : Have you tacked this issue in order to close it?
Based on your discussion, and further studies, in brief, the rule is "don't break the left to right order", and in case of the primary action on the right, it can be done but with providing a visual distinction between these actions thus maintaining the same order "the left to right", in parallel there is a need to use audio information with verbal description for people with disability in reading, or/and cannot see/look at the visual content as told in http://www.w3.org/TR/WCAG10/, http://www.w3.org/TR/wai-aria-practices/ including datepicker, and https://groups.google.com/forum/#!topic/jquery-a11y/A1XXyqnmJPc
The following in greater detail supports the above:
1) primary action on the left and secondary action on the right; here are examples based on:
    http://wet-boew.github.io/wet-boew-styleguide/v4/design/buttons-en.html, where the Primary button is set on left side and using sizing and colour options (that means as larger and active) 
   and see the summary on http://www.smashingmagazine.com/2009/10/13/call-to-action-buttons-examples-and-best-practices/
   The above can be supported by http://www.w3.org/TR/WCAG20/ 1.4.1 Use of Color; Guideline 2.2 Enough Time, Guideline 3.3 Input Assistance
NOTE: Use audio information with verbal description for people with disability in reading, and cannot see the visual content, according to http://www.w3.org/TR/WCAG10/
2) in case of switching the primary action on the right, it can be done but with providing a visual distinction between these actions thus again maintaining the same order, see on http://www.uie.com/articles/previous_next_luke/ 

Others view on the matter
3) "While the primary goal of most Web form designs is to get people through a form as quickly and painlessly as possible, there are situations where slowing people down is advisable. When choosing between primary and secondary actions, visual distinctions are a useful method for helping people make good choices." -  see on http://www.lukew.com/ff/entry.asp?571

4) "Therefore, it’s important that primary actions on your interface have the strongest visual weight, and that secondary actions have the weakest visual weight. The primary action is normally the one that completes the user’s task. However, when the user is capable of doing an action that’s permanent and irreversible, the primary action is actually the ‘Cancel’ button." - http://uxmovement.com/buttons/visual-weight-of-primary-and-secondary-action-buttons/

**Comment by neoinsight** [comment]
@hsrudnicki That's a terrific summary of the issues. I'm not ready to close this issue yet because I'm waiting to: 
1. test the form with screenreader users - this would require that @thomasgohard implement the order and suggested DOM reversal and CSS positioning that he and @LaurentGoderre discuss above in the usability testing form at http://thomasgohard.github.io/web-form-validation-test/index-en.html (it still shows Submit then Previous).

2. Above, I suggested a demonstration form that would implement a broad range of this and other design patterns for the GC design community, and there was support for this idea from @pcwsmith and others. However, that takes time and effort.  At minimum, what I'd like to suggest is that @thomasgohard add a link to the usability testing form from the WET DEMO's page for Form Validation Input, with some reference to continous improvement and ideas on how to put these input elements together into a form.

**Comment by thomasgohard** [comment]
@neoinsight I've changed the button order and updated the form.

**Comment by neoinsight** [comment]
@thomasgohard Super! First item above (I seem to have accidentally created two item '1's) is closed.

**Comment by hsrudnicki** [comment]
also see/take into consideration: https://github.com/wet-boew/wet-boew/issues/3623 - Split demos to single page each

**Comment by hsrudnicki** [comment]
@thomasgohard and others: Make Stale and close this issue or otherwise?

**Comment by hsrudnicki** [comment]
Label this issue as "Going Stale"?  Either way, please again update the status of this issue whether this issue can be closed as resolved/fixed or if otherwise?  Thank you

**Comment by neoinsight** [comment]
@hsrudnicki  The current demo form for testing purposes is at http://thomasgohard.github.io/web-form-validation-test/index-en.html but its for testing, so there are some things in there that are not solid yet. Hmmm... 
@shawnthompson We'd like to make sure people using the form validation elements get more help and ideas about how to use them. What I really need is a Testing form, and a Demo form linked from the Form Validation documentation page.  Is it possible for you to fork/copy the repo at http://thomasgohard.github.io/web-form-validation-test/index-en.html. to make a demo form, and give me editing privileges? Then I'll use the original one for testing purposes. 
@pcwsmith - I would like to get this in place in time for Codefest. Make sense?

**Comment by pcwsmith** [comment]
@neoinsight makes sense to me. As we learn/solidify via testing, the improvements make their way to the demo... Also link the demo from the Canada.ca theme working examples? http://wet-boew.github.io/themes-dist/GCWeb/index-en.html @DK-TBS take note also!

**Comment by hsrudnicki** [comment]
Please update this issue's status again for this year whether this can be closed or otherwise?  Thank you

**Comment by neoinsight** [comment]
Closing this issue - form validation component issues are posted elsewhere. A demonstration form is not posted on WET or GCWEb but is in progress here:
 https://neoinsight.github.io/ux/form-templates/index-en.html

**Comment by kodecount** [comment]
Just my personal opinion but splitting a form like this would seem like a nightmare on the back end because each `next` button is a form submission. You could potentially lose data or data may not be properly connected with each set of previous information.

I'm talking about this link: https://neoinsight.github.io/ux/form-templates/index-en.html

**Comment by neoinsight** [comment]
@kodecount, thanks, I must admit my focus has been purely on the components, someone built this originally this way (with no server back-end) and I don't have the expertise to change it. So we will be calling for help on that in the future!

Sent from my iPad

On Apr 21, 2017, at 9:46 PM, Kody <notifications@github.com<mailto:notifications@github.com>> wrote:


Just my personal opinion but splitting a form like this would seem like a nightmare on the back end because each next button is a form submission. You could potentially lose data or data may not be properly connected with each set of previous information.

I'm talking about this link: https://neoinsight.github.io/ux/form-templates/index-en.html
