### ISSUE TITLE
Enforce a button size minimum to ensure mobile usability?

### ISSUE THREAD

**Issue by neoinsight** [wet-boew/GCWeb#963]
In recent usability testing, several participants missed the Go button on this page http://webcast.international.gc.ca/cpc/bci/canada/test/home-en.html . It seems to be the same size as this one on the Travel page http://travel.gc.ca/ . 

In the image below, the participant has missed the Go button and ends up accidentally clicking the topic link below it. 
![fat fingers go button too small](https://cloud.githubusercontent.com/assets/1855584/6812908/58754ef6-d248-11e4-8ca5-8724de49ff4d.png)

Is there any way a size minimum could be imposed on buttons to ensure they don't drop below a touch target minimum?  Certainly this one could have at least been wider. 

@pcwsmith - perhaps there is someone from Travel to copy here too?

**Comment by thomasgohard** [comment]
@neoinsight minimum sizes were already specified a couple of years ago. From memory, it's 8mm × 8mm and a minimum of 2mm between touch targets.

**Comment by neoinsight** [comment]
@thomasgohard Ah, I thought you probably had minimums. But are those minimum sizes usable? How do I or a designer tell if that Go button meets that requirement?

**Comment by thomasgohard** [comment]
Those minimums are based on a number of sources I looked at a couple of years ago, all of which are conveniently summarised by Luke Wroblewski: http://www.lukew.com/ff/entry.asp?1085.

This more recent article I just found recommends 8mm to 10mm between touch targets: http://www.uxmatters.com/mt/archives/2013/03/common-misconceptions-about-touch.php. That seems a bit much though.

I measured the size of the Go button on the page you referenced. It's 7mm × 5mm, and 4mm from the link below it. So the button is smaller than the minimum touch target size, but at a greater distance than the minimum distance.

For measuring the sizes, I just used a tape measure.

One thing I'm noticing on the page is that the content jumps around every couple of seconds or so. At first I though it was because I was accidentally touching the screen with the tape measure. But it's because the two panels in the carousel don't have the same height: One panel is 11px shorter than the other. I wonder if that could have been a factor in the mis-touches you observed. That jump of 11 pixels translates to moving the button and link below it up and down by about 7mm on my phone. So, if a user tries to tap the button at same time as the panels change in the carousel, the link would now be in the position when the button used to be.

**Comment by helenepotvin** [comment]
Thank you for the information. I've copied travel on this issue. We'll adjust the button and carousel.

**Comment by shawnthompson** [comment]
@thomasgohard If they are just using the default Bootstrap classes for buttons, shouldn't we fix this upstream?

**Comment by thomasgohard** [comment]
We could by setting a `min-height` and a `min-width` on the button classes.

**Comment by neoinsight** [comment]
@thomasgohard Great idea to set a min-height and width - prevent errors - using a tape measure is just too hard and requires remembering after the fact. 
@helenepotvin Usability participants were bothered by the carousel causing jumps as well, so glad to hear that can be adjusted.

**Comment by hsrudnicki** [comment]
@neoinsight @thomasgohard @shawnthompson : If this issue had been implemented then it's ready for closing, can you closed it?

**Comment by thomasgohard** [comment]
@hsrudnicki that has yet to be implemented.
