### ISSUE TITLE
Section Menus - do not distinguish between levels of navigation

### ISSUE THREAD

**Issue by SLaverty** [wet-boew/GCWeb#976]
We have had a question from our Web Services team regarding the CSS used for the "Section Menu" on WET 4 templates  (see http://wet-boew.github.io/themes-dist/GCWeb/partners/index-en.html).  We found it useful to use colour and margin spaces within the Section Menus on our WET 4 sites to better identify to users their location in the site and to understand the site structure (IA) (see image of Canada150 site, below).  

In our current implementation of WET 4, we used custom CSS code from Immigration (see code snips, below) to achieve the changes.  As we are now moving to remove all custom CSS from the WET 4 sites, we would like to propose the inclusion of this custom CSS in the templates on github.   The current implementation of the Section Menus does not distinguish between levels of navigation, or the Section Name (screenshot from github, below). Although we don't need three levels of navigation across our topic/destination content, we do need it for special event sites where all content hangs off a left nav.   Can someone confirm if section menus can be adapted to allow 3 distinguishing levels of navigation?     

http://canada150.gc.ca/eng/1408122550222/1408364702611

![image](https://cloud.githubusercontent.com/assets/12070853/7279068/3d2a9560-e8e7-11e4-96ce-b9d6c0d1fa2c.png)

GITHUB IMPLEMENTATION OF SECTION MENU WITHOUT CUSTOM CSS

![image](https://cloud.githubusercontent.com/assets/12070853/7279079/54cd0338-e8e7-11e4-8480-8d054fbfb703.png)

CUSTOM CSS CODE SNIP

This is to add a top level blue background, and push the other two standard ones down a level.  Take from Immigration site
.wb-topnav {
    background-color: #335075 !important;
    color: #ffffff !important;
}

We needed an additional level, for Canada150, so we added this code

.wb-nav3 {
    background-color: rgb(245, 245, 245) !important;
    padding-left: 3em !important;

}

#wb-sec .list-group a.wb-nav3.wb-navcurr, #wb-sec .list-group a.wb-nav3[href]:focus, #wb-sec .list-group a.wb-nav3[href]:hover {
    background-color: gray !important;;
    color: #fff !important;;
} 

Contact:  
Sandra Laverty
Culture, history & sport theme
sandra.laverty@pch.gc.ca
819-934-1334

**Comment by SLaverty** [comment]
Ooops -- second image copied as the same as the first.  Here is the correct one:

![image](https://cloud.githubusercontent.com/assets/12070853/7279213/434df5b2-e8e8-11e4-9725-578432678716.png)

**Comment by thomasgohard** [comment]
The section menu only allows one level of links as per Section 6.5.2 of the Content and information architecture specification.

**Comment by neoinsight** [comment]
@SLaverty This level issue is restricted because of mobile. I wonder if you are also aware that the left nav is not visible at all in mobile view - you mention that all content hangs off of it? As much as possible, a Mobile First design approach is recommended - that means the design works beautifully on a smart phone, and then you can enhance it for desktop views in ways that don't destroy the mobile experience. 

If you are suggesting that moving around within your pages requires use of the left menu, then mobile users will be unable to move around unless they figure out to click on the menu icon at the top of the page. 

For Mobile First ideas, the Weather pages have some alternatives to left menus (the panel at the bottom of the page) that worked well in usability tests with both mobile and desktop web visitors.

**Comment by suzanneIRB** [comment]
Most of our tables on our website use <colgroup><col></colgroup> to format our tables, such as alignment. However is has come to our attention that the alignment classes with WET 4, ie. text-right, text-left, text-center, do not work when used in the <col> tag. Can the wb- stylesheet be adjusted to include <col> to work with theses classes?

**Comment by hsrudnicki** [comment]
@SLaverty @thomasgohard @neoinsight:
This issue can be merged with issues: #776 and #6502 in regards to coding and css (for color)
https://github.com/wet-boew/GCWeb/issues/776
https://github.com/wet-boew/wet-boew/issues/6502

**Comment by hsrudnicki** [comment]
https://github.com/wet-boew/GCWeb/issues/971 - see ongoing discussion about Navigation, which should help in solving and closing this issue

**Comment by pcwsmith** [comment]
note that #971 is about an in-page nav pattern applicable to a step-by-step process, rather than a left menu pattern used to bring related content together. Either way, both patterns only work with a single level of depth, given the constraints we are working within (i.e. small screens need to be taken into account) - pretty much precludes multi-level menu patterns. Means that the solution likely lies elsewhere - re-structuring the content or re-organizing the IA for example.

**Comment by hsrudnicki** [comment]
Yes, merging the issues may create complex situations, that will need re-structuring and/or re-organizing, depending on point of observation/view and/or use of granularity.
Based on this issue original comment, it's asking about inclusion of custom CSS within Section Menus on WET 4 sites / github templates to distinguish between levels of navigation, and the next question is about 3 levels of navigation and use of graphic design to distinguish them.

**Comment by hsrudnicki** [comment]
For example, to see others unless it's redundant pls ignore:
http://www.smashingapps.com/2014/11/26/37-responsive-navigation-menus-plugins-tutorials.html
http://www.smashingmagazine.com/2013/09/11/responsive-navigation-on-complex-websites/
http://ux.stackexchange.com/questions/73692/mobile-multi-level-navigation-with-split-button-access-to-sub-levels

**Comment by hsrudnicki** [comment]
Please update this issue's status as well, whether this issue remains opened or closed as resolved/fixed?
In addition, label this issue as "Going Stale"?  Thank you

**Comment by pcwsmith** [comment]
Safe to close this one as the issues reported here are being worked on over in #1022 ?

**Comment by hsrudnicki** [comment]
Closed based on the last comment.
