### ISSUE TITLE
Section menu - mobile alternative

### ISSUE THREAD

**Issue by pcwsmith** [wet-boew/GCWeb#995]
As discussed yesterday with @thomasgohard @lucas-hay @neoinsight @dk-tbs @nrustad92 @LaurentGoderre , a small screen alternative for the WET section menu component is required.

This arises out of usability testing that @neoinsight has undertaken on tasks dependent on this component. The basic finding is that users do not expect local nav to be included in the mobile header menu (under the hamburger icon), as this is perceived as a global element.

The ultimate recommendation is to phase out left navs altogether, but this will take some time to accomplish as far too many GC sites are too dependent on section menus in their designs at present. As a transitional measure that would allow GC sites to transition to WET 4 more quickly, responsively adapting the large-screen section menu into a small screen on-page component (at the bottom of the main content area) is the best way forward.

So, as agreed @dk-tbs will tackle the design aspect, creating mockups for how an small-screen, on-page equivalent to section menus would work. Then Service Canada will work to implement in WET. The anticipated timeline would be for the September release of WET (v4.0.18).

**Comment by neoinsight** [comment]
In further discussion on this with M. from Business Theme, the issue of very long section menus and menus with levels came up. Despite WET4 not supporting levels in menus, WET4 pages with left nav menus have been created on many sites.  

For examples of long menus with levels, see Corporations Canada http://www.ic.gc.ca/eic/site/cd-dgc.nsf/eng/h_cs03926.html or Canada 150 http://canada.pch.gc.ca/eng/1359662086503/ or GetCyberSafe http://www.getcybersafe.gc.ca/cnt/rsks/nln-ctvts/index-en.aspx (now that's long!). 

In all these cases, it is only the lowest level of the menu (e.g. the deepest `<ul>`) that is really 'section' navigation. All of the other left menu options are navigation to other layers/topics. But in all of these example WET4 pages, the entire left nav is being swapped into the hamburger menu. The unordered lists turn into detail/summary items. 

But swapping these all into an ankle menu on the mobile page is bad news - they'll be huge! Right now, they are hidden in the hamburger and that's good. Bringing them out into view on mobile creates a different problem. And how to format them - yikes. What M. and I were discussing is that >only the lowest level UL should be swapped in to an on-page ankle. Everything else in the menu should be ignored. 

@dk-tbs, you'll want to keep this in mind as you design. 

Thoughts?

**Comment by thomasgohard** [comment]
These pages have menus that contain both siblings and children of the current page. I though we were only allowing siblings in the secondary navigation. Also, the PCH example has at least three level. We only allow one level. Once those menu are made compliant, they would be a lot shorter.

**Comment by neoinsight** [comment]
@thomasgohard Agree that these menus are not compliant. They are in WET4 though, so am concerned that they will have trouble redoing the IA before they onboard.

**Comment by thomasgohard** [comment]
These sites may be using WET4, but none of the menus are coded according to the WET4 spec for the secondary menu. The PCH menu also uses non-WET styles, which they will not have once they onboard.

For the Corporations site, with three exceptions, every sub-link is also on the parent-level page itself. If they just add those three links to the appropriate pages and redo the menu to only siblings, they're done.

For the CyberSafe site, all the sub-links are also on the parent-level page itself. If they redo the menu to only siblings, they're done.

The Canada 150 site is more messy, but I don't think it would take that much to make it comply.

**Comment by neoinsight** [comment]
@thomasgohard Fair enough. What you're saying is that they need to put the effort in, and that often, it's not that much effort since these menus are so often duplicating the links on the page, or parents rather than sublinks.

**Comment by thomasgohard** [comment]
@neoinsight in many cases, yes, it means very little effort. Any of those should be identified and fixed.

For those where it will be more effort, we'd have to look at them on a case-by-case basis. But if their markup doesn't comply to the WET4 spec or they have custom CSS, then they probably won't be able to onboard as-is anyways.

**Comment by DK-TBS** [comment]
I'm thinking that unless we have compelling reasons to do otherwise, the section menu should have the same look/feel in the small-screen version as it does on large screens.  This way, visitors may be able to identify it more easily, if they are already used to seeing it on desktop displays.  Lisa, I've used the Canada 150 section as an example, to illustrate how it might look when bumped to the bottom.  

Any objections?  Suggestions?  Comments?  All are welcome.

![section menu - small screen](https://cloud.githubusercontent.com/assets/9662127/9066816/bc99f9c8-3aa7-11e5-914c-3eb15d9c0658.jpg)

![section menu - large screen](https://cloud.githubusercontent.com/assets/9662127/9066822/c1b7e67c-3aa7-11e5-9aa3-c00d16216ae9.jpg)

**Comment by thomasgohard** [comment]
Maybe it's the headings in the menu in the mock-up, but without an indicator that it's navigation, it doesn't look like navigation to me. I'm not sure what it's supposed to be. It feels like a heading above the navigation items to give context would help.

**Comment by neoinsight** [comment]
@DK-TBS I get your point - good idea to make it look similar even though some mobile users may not cross platforms.  But @thomasgohard is right, we can't know  what the top heading on the menu will be (in this case, it is a bit confusing). Then again, I'm not sure that @thomasgohard's concern is addressable via any words at all - conveying navigation isn't a word thing, it's a graphic thing, and that's why Dave has gone this route. 

So I'd come down to supporting this approach and fine-tuning it later after some testing.

**Comment by DK-TBS** [comment]
Hi @thomasgohard!  I did want to mark the section menu with a heading on small screens, but had a hell of a time coming up with good wording for it.  "In this section" might be nice, but it's misleading because it makes it sound like the menu is for items below/inside the "activities" section.  "Related pages" is close, but conflicts with "related links" and is a bit too vague anyway.  "Section menu" was another one I considered, but it sounds... weak.  "Pages under 'Canada Day from Coast to Coast to Coast'" was nice and descriptive and accurate, but ridiculously wordy.  

I'm a bit stuck on it, but will ponder it some more.  Perhaps we'll end up just running with it and doing some testing, as Lisa @neoinsight suggests...

**Comment by hsrudnicki** [comment]
@pcwsmith and others: Is this above still an issue?  Either way, please update this issue's status whether this issue, referenced with the other 1022 as closed issue, can be closed as well as resolved/fixed or if otherwise?  Thank you
Additionally label this issue as "Going Stale"?

**Comment by pcwsmith** [comment]
I think it's safe to close this one as it was resolved via #1022
