### ISSUE TITLE
Mobile menu - consider adding the word 'menu'

### ISSUE THREAD

**Issue by pcwsmith** [wet-boew/GCWeb#996]
Suggested enhancement arising from recent usability testing by @neoinsight. Lower in priority, but would help more users understand what the hamburger icon actually represents. Something along these lines:

![mobile menu suggestion](https://cloud.githubusercontent.com/assets/5454117/8730073/c4815428-2bbc-11e5-843c-e3525cc12ee8.png)

**Comment by pcwsmith** [comment]
rationale is that when menus are visible, they're used successfully. Also appears to be an emerging convention around including the word menu. Some examples:

![mobile menu suggestion - examples](https://cloud.githubusercontent.com/assets/5454117/8730179/5809c306-2bbd-11e5-8dc9-7d5072d1b7ab.png)

**Comment by pcwsmith** [comment]
Clarification: "Consider adding the word ‘Menu’ to the right of the hamburger icon, like many Bootstrap-based sites. Do NOT split up search and menu – they work beautifully together." (from usability report by @neoinsight)

**Comment by pjackson28** [comment]
Note that menu would be an inaccurate and potentially confusing label because the menu includes search as well. Also the hidden/hover text is "Search and menus" so would conflict with a "Menu" label. Note that the hidden/hover text can change if components are disabled (e.g., "Search label removed if search field is removed and menus label is removed if menus are removed). Now if we go with "Search and menus" then we'll definitely run into space issues.

**Comment by pcwsmith** [comment]
What we are seeing in usability sessions is that people understand the magnifying glass to mean search. It's the hamburger that's mystery meat (ha)

**Comment by neoinsight** [comment]
@pjackson28 In case @pcwsmith's amusing mystery meat comment isn't clear enough - Intent here is for sighted people to have the same experience as those hearing the hover text 'Search and menus'. So nothing should change for hidden hover text - just that the word Menus is added to the visible icon that is currently glass-hamburger. The icon would become 'glass-hamburger-word'.

**Comment by LaurentGoderre** [comment]
What about using Navigation since search and menu are navigation mechanism?

**Comment by neoinsight** [comment]
@LaurentGoderre hmm, there are no web conventions around that like there are for 'menu'. It tends to only be used by tech-folk. As shown in the images above, the word 'menu' is what's getting used.

**Comment by pjackson28** [comment]
@neoinsight Looking at the images above, it looks like goodfood is providing a "Search" label for the search icon and a "Menu" label for the menu icon while The Atlantic is only doing that for the menu icon. Is the recommendation to add the visible label for the menu icon even though the hidden text has both? From the technical standpoint it is easiest to make the hidden text visible rather than adding another label (so "Search and menus") but that of course would take up a lot more real estate than just "Menu" (also note that there is usually at least two menus in the mobile panel).

**Comment by neoinsight** [comment]
@pjackson28 hmm, that's a tricky one. I didn't realize it's easier from a technical standpoint to make the hidden text visible. And you're right, that would take up a lot more real estate. Not keen on that, especially since the search icon is working so well. 

Re 'menus' versus 'menu', it actually took me a minute to get the distinction you are making, because to me (and to the users I've seen), there is only one menu that drops down, the bottom part just happens to be in a different color. The idea that they are actually different menus is pretty sophisticated and relies on knowing how it looks on a computer screen.Interestingly, most of the mobile participants called it a 'mobile site' - they're not aware it's responsive and would look different on a monitor.

So 'Menu' conveys it well enough and matches the convention growing out there. 

Compared to some of the other usability issues like the date picker or the auto-complete ( particularly for the maps), this is not a high priority. So if it's technically difficult, I would suggest leaving it and focusing on those issues. Yesterday's participant was totally stymied by trying to put a year into the date picker...

**Comment by neoinsight** [comment]
@pcwsmith Suggest closing this, no longer think it's necessary. The SearchBurger is working nicely.
